### ISSUE TITLE
Deployment to QA failed

### ISSUE THREAD

**Issue by fhe-fr** [microsoft/MLOpsPython#116]
ENOENT: no such file or directory, stat 'd:\a\r1\a\_ci-build\mlops-pipelines\code\scoring\deployment_config_aci.yml'

![image](https://user-images.githubusercontent.com/16428049/69620653-f7859e00-103d-11ea-9f1e-40792524a974.png)

2019-11-26T09:47:40.6248243Z ##[section]Starting: Azure ML Model Deploy
2019-11-26T09:47:40.6361728Z ==============================================================================
2019-11-26T09:47:40.6361837Z Task         : AzureML Model Deploy
2019-11-26T09:47:40.6361892Z Description  : AzureML Deploy Model
2019-11-26T09:47:40.6361956Z Version      : 0.8.19
2019-11-26T09:47:40.6362005Z Author       : ms-air-aiagility
2019-11-26T09:47:40.6362072Z Help         : https://marketplace.visualstudio.com/items?itemName=ms-air-aiagility.private-vss-services-azureml&ssr=false#overview
2019-11-26T09:47:40.6362160Z ==============================================================================
2019-11-26T09:47:41.1059150Z { Error: ENOENT: no such file or directory, stat 'd:\a\r1\a\_ci-build\mlops-pipelines\code\scoring\deployment_config_aci.yml'
2019-11-26T09:47:41.1059416Z     at Error (native)
2019-11-26T09:47:41.1060050Z     at Object.fs.statSync (fs.js:1000:11)
2019-11-26T09:47:41.1060535Z     at AMLDeployParams.validateFileAndExtension (d:\a\_tasks\AMLModelDeploy_d9237456-3431-4c1d-b7bf-d6b937425f0f\0.8.19\operations\AMLDeployParams.js:214:17)
2019-11-26T09:47:41.1061289Z     at AMLDeployParams.validateDeployConfig (d:\a\_tasks\AMLModelDeploy_d9237456-3431-4c1d-b7bf-d6b937425f0f\0.8.19\operations\AMLDeployParams.js:162:14)
2019-11-26T09:47:41.1061697Z     at AMLDeployParams.<anonymous> (d:\a\_tasks\AMLModelDeploy_d9237456-3431-4c1d-b7bf-d6b937425f0f\0.8.19\operations\AMLDeployParams.js:86:30)
2019-11-26T09:47:41.1062079Z     at step (d:\a\_tasks\AMLModelDeploy_d9237456-3431-4c1d-b7bf-d6b937425f0f\0.8.19\operations\AMLDeployParams.js:33:23)
2019-11-26T09:47:41.1062436Z     at Object.next (d:\a\_tasks\AMLModelDeploy_d9237456-3431-4c1d-b7bf-d6b937425f0f\0.8.19\operations\AMLDeployParams.js:14:53)
2019-11-26T09:47:41.1062786Z     at d:\a\_tasks\AMLModelDeploy_d9237456-3431-4c1d-b7bf-d6b937425f0f\0.8.19\operations\AMLDeployParams.js:8:71
2019-11-26T09:47:41.1063153Z     at __awaiter (d:\a\_tasks\AMLModelDeploy_d9237456-3431-4c1d-b7bf-d6b937425f0f\0.8.19\operations\AMLDeployParams.js:4:12)
2019-11-26T09:47:41.1063552Z     at AMLDeployParams.getDeploymentParameters (d:\a\_tasks\AMLModelDeploy_d9237456-3431-4c1d-b7bf-d6b937425f0f\0.8.19\operations\AMLDeployParams.js:81:16)
2019-11-26T09:47:41.1063885Z   errno: -4058,
2019-11-26T09:47:41.1064207Z   code: 'ENOENT',
2019-11-26T09:47:41.1064525Z   syscall: 'stat',
2019-11-26T09:47:41.1064873Z   path: 'd:\\a\\r1\\a\\_ci-build\\mlops-pipelines\\code\\scoring\\deployment_config_aci.yml' }
2019-11-26T09:47:41.1117283Z ##[error]ENOENT: no such file or directory, stat 'd:\a\r1\a\_ci-build\mlops-pipelines\code\scoring\deployment_config_aci.yml'
2019-11-26T09:47:41.1125820Z (node:4604) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Failed popd: popd: directory stack empty
2019-11-26T09:47:41.1150072Z 
2019-11-26T09:47:41.1155490Z Reverting to original directory.....
2019-11-26T09:47:41.1161418Z popd: directory stack empty
2019-11-26T09:47:41.1177117Z 
2019-11-26T09:47:41.1194028Z ##[section]Finishing: Azure ML Model Deploy

**Comment by fhe-fr** [comment]
NA

**Comment by smandaric** [comment]
I'm having the same issue. How did you resolve this @fhe-fr ?
