### ISSUE TITLE
Deployment to QA failed

### ISSUE THREAD

**Issue by fhe-fr** [microsoft/MLOpsPython#117]
ENOENT: no such file or directory, stat '/home/vsts/work/r1/a/_ci-build/mlops-pipelines/code/scoring/deployment_config_aci.yml'

******************************************************************************
2019-11-26T12:52:16.5473405Z ##[section]Starting: Azure ML Model Deploy
2019-11-26T12:52:16.5478581Z ==============================================================================
2019-11-26T12:52:16.5478685Z Task         : AzureML Model Deploy
2019-11-26T12:52:16.5478763Z Description  : AzureML Deploy Model
2019-11-26T12:52:16.5478820Z Version      : 0.8.19
2019-11-26T12:52:16.5478891Z Author       : ms-air-aiagility
2019-11-26T12:52:16.5478965Z Help         : https://marketplace.visualstudio.com/items?itemName=ms-air-aiagility.private-vss-services-azureml&ssr=false#overview
2019-11-26T12:52:16.5479065Z ==============================================================================
2019-11-26T12:52:16.8866440Z { Error: ENOENT: no such file or directory, stat '/home/vsts/work/r1/a/_ci-build/mlops-pipelines/code/scoring/deployment_config_aci.yml'
2019-11-26T12:52:16.8866750Z     at Error (native)
2019-11-26T12:52:16.8866819Z     at Object.fs.statSync (fs.js:1000:11)
2019-11-26T12:52:16.8869025Z     at AMLDeployParams.validateFileAndExtension (/home/vsts/work/_tasks/AMLModelDeploy_d9237456-3431-4c1d-b7bf-d6b937425f0f/0.8.19/operations/AMLDeployParams.js:214:17)
2019-11-26T12:52:16.8869853Z     at AMLDeployParams.validateDeployConfig (/home/vsts/work/_tasks/AMLModelDeploy_d9237456-3431-4c1d-b7bf-d6b937425f0f/0.8.19/operations/AMLDeployParams.js:162:14)
2019-11-26T12:52:16.8870255Z     at AMLDeployParams.<anonymous> (/home/vsts/work/_tasks/AMLModelDeploy_d9237456-3431-4c1d-b7bf-d6b937425f0f/0.8.19/operations/AMLDeployParams.js:86:30)
2019-11-26T12:52:16.8870668Z     at step (/home/vsts/work/_tasks/AMLModelDeploy_d9237456-3431-4c1d-b7bf-d6b937425f0f/0.8.19/operations/AMLDeployParams.js:33:23)
2019-11-26T12:52:16.8871044Z     at Object.next (/home/vsts/work/_tasks/AMLModelDeploy_d9237456-3431-4c1d-b7bf-d6b937425f0f/0.8.19/operations/AMLDeployParams.js:14:53)
2019-11-26T12:52:16.8871441Z     at /home/vsts/work/_tasks/AMLModelDeploy_d9237456-3431-4c1d-b7bf-d6b937425f0f/0.8.19/operations/AMLDeployParams.js:8:71
2019-11-26T12:52:16.8871823Z     at __awaiter (/home/vsts/work/_tasks/AMLModelDeploy_d9237456-3431-4c1d-b7bf-d6b937425f0f/0.8.19/operations/AMLDeployParams.js:4:12)
2019-11-26T12:52:16.8872275Z     at AMLDeployParams.getDeploymentParameters (/home/vsts/work/_tasks/AMLModelDeploy_d9237456-3431-4c1d-b7bf-d6b937425f0f/0.8.19/operations/AMLDeployParams.js:81:16)
2019-11-26T12:52:16.8872510Z   errno: -2,
2019-11-26T12:52:16.8872752Z   code: 'ENOENT',
2019-11-26T12:52:16.8872959Z   syscall: 'stat',
2019-11-26T12:52:16.8873249Z   path: '/home/vsts/work/r1/a/_ci-build/mlops-pipelines/code/scoring/deployment_config_aci.yml' }
2019-11-26T12:52:16.8948140Z ##[error]ENOENT: no such file or directory, stat '/home/vsts/work/r1/a/_ci-build/mlops-pipelines/code/scoring/deployment_config_aci.yml'
2019-11-26T12:52:16.8961783Z Reverting to original directory.....
2019-11-26T12:52:16.8961920Z (node:3335) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Failed popd: popd: directory stack empty
2019-11-26T12:52:16.8961998Z 
2019-11-26T12:52:16.8962110Z popd: directory stack empty
2019-11-26T12:52:16.8962149Z 
2019-11-26T12:52:16.8964165Z ##[section]Finishing: Azure ML Model Deploy

**Comment by smandaric** [comment]
I'm having the same issue

**Comment by fhe-fr** [comment]
Still pending issue

**Comment by fhe-fr** [comment]
The issue is resolved. I did 2 things:
1) fork again with the latest version
2) the name of my training pipeline wasn't "ci_build" which is used in the path during th etask definition:  $(System.DefaultWorkingDirectory)/_ci-build/...
