### ISSUE TITLE
Install Jupyter notebook 

### ISSUE THREAD

**Issue by yghassoun** [microsoft/MLOpsPython#183]
I am trying to install Jupyter notebook but always i got an error
C:\>pip3 install --user jupyter
Fatal error in launcher: Unable to create process using '"c:\osgeo4~1\bin\python3.exe"  "C:\PROGRA~1\QGIS3~1.10\apps\Python37\Scripts\pip3.exe" install --user jupyter'

Then i have used:
C:\>python -m pip install jupyter
ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\photogrammetrie\AppData\Roaming\Python\Python37\site-packages\pip\_internal\cli\base_command.py", line 186, in _main
    status = self.run(options, args)
  File "C:\Users\photogrammetrie\AppData\Roaming\Python\Python37\site-packages\pip\_internal\commands\install.py", line 258, in run
    isolated_mode=options.isolated_mode,
  File "C:\Users\photogrammetrie\AppData\Roaming\Python\Python37\site-packages\pip\_internal\commands\install.py", line 604, in decide_user_install
    if site_packages_writable(root=root_path, isolated=isolated_mode):
  File "C:\Users\photogrammetrie\AppData\Roaming\Python\Python37\site-packages\pip\_internal\commands\install.py", line 549, in site_packages_writable
    test_writable_dir(d) for d in set(get_lib_location_guesses(**kwargs))
  File "C:\Users\photogrammetrie\AppData\Roaming\Python\Python37\site-packages\pip\_internal\commands\install.py", line 549, in <genexpr>
    test_writable_dir(d) for d in set(get_lib_location_guesses(**kwargs))
  File "C:\Users\photogrammetrie\AppData\Roaming\Python\Python37\site-packages\pip\_internal\utils\filesystem.py", line 140, in test_writable_dir
    return _test_writable_dir_win(path)
  File "C:\Users\photogrammetrie\AppData\Roaming\Python\Python37\site-packages\pip\_internal\utils\filesystem.py", line 153, in _test_writable_dir_win
    fd = os.open(file, os.O_RDWR | os.O_CREAT | os.O_EXCL)
PermissionError: [Errno 13] Permission denied: 'C:\\PROGRA~1\\QGIS3~1.10\\apps\\Python37\\Lib\\site-packages\\accesstest_deleteme_fishfingers_custard_r4ci05'

Any help please?

**Comment by dtzar** [comment]
I'm sorry, but this has nothing to do with this repository, only a problem with you installing Jupyter on your local machine.  I might try to install without the --user switch.
