### ISSUE TITLE
AutoML error missing Parameter Path

### ISSUE THREAD

**Issue by azure-walker** [microsoft/MLOpsPython#309]
AutoML fails to run. Get an error message specifying that Parameter path now found. I included the error log from ML Portal.

[2020-07-09 15:17:12Z] Failed to start the job because of error: Parameter path not found, stack_trace:    at Microsoft.Aether.AutoMLCloud.Service.StructuredInterfaceParser.GetParameterValue(String jobId, Dictionary`2 parameters, String name) in d:\dbs\sh\Ae\0625_091617\cmd\f\src\aether\platform\backendV2\BlueBox\Clouds\AutoMLCloud\Service\StructuredInterfaceParser.cs:line 612
   at Microsoft.Aether.AutoMLCloud.Service.StructuredInterfaceParser.GetAutoMLSettings(Dictionary`2 parameterValues, AutoMLJobMetadata job) in d:\dbs\sh\Ae\0625_091617\cmd\f\src\aether\platform\backendV2\BlueBox\Clouds\AutoMLCloud\Service\StructuredInterfaceParser.cs:line 63
   at Microsoft.Aether.AutoMLCloud.Service.StructuredInterfaceParser.ParseStructuredInterface(AutoMLJobMetadata job) in d:\dbs\sh\Ae\0625_091617\cmd\f\src\aether\platform\backendV2\BlueBox\Clouds\AutoMLCloud\Service\StructuredInterfaceParser.cs:line 28
   at Microsoft.Aether.AutoMLCloud.Service.JobProcessor.InitializeNewJob(AutoMLJobMetadata job) in d:\dbs\sh\Ae\0625_091617\cmd\f\src\aether\platform\backendV2\BlueBox\Clouds\AutoMLCloud\Service\JobProcessor.cs:line 232
   at Microsoft.Aether.AutoMLCloud.Service.JobProcessor.StartNewJobAsync(AutoMLJobMetadata job) in d:\dbs\sh\Ae\0625_091617\cmd\f\src\aether\platform\backendV2\BlueBox\Clouds\AutoMLCloud\Service\JobProcessor.cs:line 161

**Comment by shivp950** [comment]
We're following up with the AutoML team on this issue, we'll provide an update as soon as we can. Thanks for your patience!
