### ISSUE TITLE
we deploy a model to aci, the container is crashing due to ModuleNotFoundError: No module named 'ruamel'

### ISSUE THREAD

**Issue by mouhannadali** [microsoft/MLOpsPython#332]
when I try to deploy to aci, I am getting the following error:

Starting gunicorn 19.9.0
Listening at: http://127.0.0.1:31311 (13)
Using worker: sync
worker timeout is set to 300
Booting worker with pid: 46
Exception in worker process
Traceback (most recent call last):
  File "/opt/miniconda/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/opt/miniconda/lib/python3.6/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/opt/miniconda/lib/python3.6/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/opt/miniconda/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/opt/miniconda/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/opt/miniconda/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/opt/miniconda/lib/python3.6/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/var/azureml-server/wsgi.py", line 1, in <module>
    import create_app
  File "/var/azureml-server/create_app.py", line 3, in <module>
    from app import main
  File "/var/azureml-server/app.py", line 31, in <module>
    import main as user_main
  File "/var/azureml-app/main.py", line 12, in <module>
    driver_module_spec.loader.exec_module(driver_module)
  File "/var/azureml-app/audit_anomaly/scoring/score.py", line 30, in <module>
    from azureml.core.model import Model
  File "/opt/miniconda/lib/python3.6/site-packages/azureml/core/__init__.py", line 13, in <module>
    from .workspace import Workspace
  File "/opt/miniconda/lib/python3.6/site-packages/azureml/core/workspace.py", line 34, in <module>
    from azureml.core.image import Image
  File "/opt/miniconda/lib/python3.6/site-packages/azureml/core/image/__init__.py", line 28, in <module>
    from .image import Image
  File "/opt/miniconda/lib/python3.6/site-packages/azureml/core/image/image.py", line 19, in <module>
    from azureml.core.model import Model
  File "/opt/miniconda/lib/python3.6/site-packages/azureml/core/model.py", line 39, in <module>
    from azureml.core.environment import Environment
  File "/opt/miniconda/lib/python3.6/site-packages/azureml/core/environment.py", line 31, in <module>
    from azureml.core.conda_dependencies import CondaDependencies, PYTHON_DEFAULT_VERSION
  File "/opt/miniconda/lib/python3.6/site-packages/azureml/core/conda_dependencies.py", line 11, in <module>
    import ruamel.yaml
ModuleNotFoundError: No module named 'ruamel'

conda_dependencies.yml:
name: audit_anomaly_training_env
dependencies:
  # The python interpreter version.
  # Currently Azure ML Workbench only supports 3.5.2 and later.
  - python=3.7.*
  # Required by azureml-defaults, installed separately through Conda to
  # get a prebuilt version and not require build tools for the install.
  # - psutil=5.6 #latest
  - pyodbc=4.0.28
      # Required packages for AzureML execution, history, and data preparation.
  - pip

  - pip:
      # Base AzureML SDK
      - azureml-sdk

      # Must match AzureML SDK version.
      # https://docs.microsoft.com/en-us/azure/machine-learning/concept-environments
      - azureml-defaults

      # Training deps
      - scikit-learn

      # Scoring deps
      - inference-schema[numpy-support]

      # MLOps with R
      - azure-storage-blob      
      - pandas==0.25.3
      - numpy==1.17.3
      - sqlalchemy==1.3.18

it is also strange why it shows python3.6 where it should be python 3.7.*

**Comment by mouhannadali** [comment]
had to install the last version of ruamel.yaml but by using --ignore-installed flag 
 RUN pip install --ignore-installed  ruamel.yaml
