### ISSUE TITLE
can't run r scripts 

### ISSUE THREAD

**Issue by helenproudloveraisingit** [microsoft/MLOpsPython#336]
We have added the r-essentials packages as instructed. However, when we try and run the r_train_r.py example it fails with this error:

Googling this there is mention that the Microsoft R client doesn't work on Ubuntu 18, so we tried changing the VM image it uses to ubuntu 16 instead of ubuntu latest, but this didn't help. 

Surely its possible to run R scripts in the Azure ML service! Is there anything else we need to change?

```

 *** caught segfault ***
address 0x38, cause 'memory not mapped'

Traceback:
 1: dyn.load(libPath)
 2: doTryCatch(return(expr), name, parentenv, handler)
 3: tryCatchOne(expr, names, parentenv, handlers[[1L]])
 4: tryCatchList(expr, classes, parentenv, handlers)
 5: tryCatch(expr, error = function(e) {    call <- conditionCall(e)    if (!is.null(call)) {        if (identical(call[[1L]], quote(doTryCatch)))             call <- sys.call(-4L)        dcall <- deparse(call)[1L]        prefix <- paste("Error in", dcall, ": ")        LONG <- 75L        sm <- strsplit(conditionMessage(e), "\n")[[1L]]        w <- 14L + nchar(dcall, type = "w") + nchar(sm[1L], type = "w")        if (is.na(w))             w <- 14L + nchar(dcall, type = "b") + nchar(sm[1L],                 type = "b")        if (w > LONG)             prefix <- paste0(prefix, "\n  ")    }    else prefix <- "Error : "    msg <- paste0(prefix, conditionMessage(e), "\n")    .Internal(seterrmessage(msg[1L]))    if (!silent && isTRUE(getOption("show.error.messages"))) {        cat(msg, file = outFile)        .Internal(printDeferredWarnings())    }    invisible(structure(msg, class = "try-error", condition = e))})
 6: try(dyn.load(libPath), silent = TRUE)
 7: tryLoadMKL(full_path, mklSymbol)
 8: fun(libname, pkgname)
 9: doTryCatch(return(expr), name, parentenv, handler)
10: tryCatchOne(expr, names, parentenv, handlers[[1L]])
11: tryCatchList(expr, classes, parentenv, handlers)
12: tryCatch(fun(libname, pkgname), error = identity)
13: runHook(".onLoad", env, package.lib, package)
14: loadNamespace(package, lib.loc)
15: doTryCatch(return(expr), name, parentenv, handler)
16: tryCatchOne(expr, names, parentenv, handlers[[1L]])
17: tryCatchList(expr, classes, parentenv, handlers)
18: tryCatch({    attr(package, "LibPath") <- which.lib.loc    ns <- loadNamespace(package, lib.loc)    env <- attachNamespace(ns, pos = pos, deps)}, error = function(e) {    P <- if (!is.null(cc <- conditionCall(e)))         paste(" in", deparse(cc)[1L])    else ""    msg <- gettextf("package or namespace load failed for %s%s:\n %s",         sQuote(package), P, conditionMessage(e))    if (logical.return)         message(paste("Error:", msg), domain = NA)    else stop(msg, call. = FALSE, domain = NA)})
19: library("RevoUtilsMath")
20: do.call("library", list(package))
21: load_if_installed("RevoUtilsMath")
22: eval(quote({    r <- getOption("repos")    if (.Platform$OS.type == "unix") {        options(download.file.method = "curl")    }    r["CRAN"] <- RevoUtils::getRevoRepos()    options(repos = r)    MRS.is.client <- RevoUtils:::isMicrosoftRClient()    isMMLSupported <- FALSE    if (identical(.Platform$OS.type, "windows")) {        isMMLSupported <- TRUE    }    if (identical(.Platform$OS.type, "unix") && length(grep("Ubuntu",         Sys.info()["version"]))) {        if (file.exists("/etc/lsb-release")) {            UbuntuReleaseInfo <- scan("/etc/lsb-release", what = "",                 sep = "\n", quiet = TRUE)            if (identical(UbuntuReleaseInfo[2], "DISTRIB_RELEASE=14.04") ||                 identical(UbuntuReleaseInfo[2], "DISTRIB_RELEASE=16.04")) {                isMMLSupported <- TRUE            }        }    }    if (identical(.Platform$OS.type, "unix") && length(grep("el7.x86_64",         Sys.info()["release"]))) {        isMMLSupported <- TRUE    }    if (!identical(system.file(package = "RevoScaleR"), "")) {        options(defaultPackages = c(getOption("defaultPackages"),             "rpart", "lattice", "RevoScaleR", if (!identical(system.file(package = "mrsdeploy"),                 "") && identical(.Platform$OS, "windows") &&                 !identical(Sys.getenv("MRS_IN_DATABASE_HOST_PLATFORM"),                   "1")) "mrsdeploy", if (!identical(system.file(package = "MicrosoftML"),                 "") && isMMLSupported) "MicrosoftML", "RevoMods",             "RevoUtils", "RevoUtilsMath"))        if (nchar(hostName <- Sys.getenv("REVOHADOOPHOST")) &&             nchar(portNumber <- Sys.getenv("REVOHADOOPPORT"))) {            RevoScaleR::rxHdfsConnect(hostName = hostName, portNumber = as.numeric(portNumber))        }    } else {        options(defaultPackages = c(getOption("defaultPackages"),             "RevoUtils"))    }    .RevoVersionShort <- Revo.version$version.string    .RevoVersionShortLen <- regexpr("^.* \\d+\\.\\d+", .RevoVersionShort,         perl = TRUE)    .RevoVersionShort <- substring(.RevoVersionShort, 1, attributes(.RevoVersionShortLen)$match)    if ("setWindowTitle" %in% getNamespaceExports("utils")) {        if (Revo.version$arch == "x86_64") {            .RevoVersionShort <- paste(.RevoVersionShort, "(64-bit)")        }        try(utils::setWindowTitle(paste(" - ", .RevoVersionShort)),             silent = TRUE)    }    if (.Platform$OS.type == "unix" && capabilities("X11")) {        browseAvail <- Sys.which(c("firefox", "mozilla", "galeon",             "opera", "xdg-open", "kfmclient", "gnome-moze-remote"))        if (any(browseAvail != "")) {            options(browser = browseAvail[which(browseAvail !=                 "")[1]])        }    }    if (.Platform$OS.type == "windows") {        options(help_type = "html")    }    load_if_installed <- function(package) {        if (!identical(system.file(package = "RevoUtilsMath"),             "")) {            do.call("library", list(package))            return(TRUE)        } else {            return(FALSE)        }    }    if (identical(system.file(package = "RevoScaleR"), "")) {        if (load_if_installed("RevoUtilsMath")) {            ncores <- RevoUtilsMath::getMKLthreads()        } else {            MROversion <- paste(Revo.version$major, Revo.version$minor,                 sep = ".")            MKLmsg <- "No performance acceleration libraries were detected. To take advantage of \nthe available processing power, also install MKL for R Open. Visit \nhttp://go.microsoft.com/fwlink/?LinkID=698301 for more details.\n"        }        if (Sys.info()["sysname"] == "Darwin") {            options(download.file.method = "libcurl")            hw.ncpu <- try(system("sysctl hw.physicalcpu", intern = TRUE))            if (!inherits(hw.ncpu, "try-error")) {                ncores <- sub("hw.physicalcpu: ", "", hw.ncpu)                MKLmsg = paste0("Multithreaded BLAS/LAPACK libraries detected. Using ",                   ncores, " cores for math algorithms.\n")            }        } else {            if (load_if_installed("RevoUtilsMath")) {                ncores <- RevoUtilsMath::getMKLthreads()                MKLmsg = ""            } else {                MROversion <- paste(Revo.version$major, Revo.version$minor,                   sep = ".")                MKLmsg <- "No performance acceleration libraries were detected. To take advantage of \nthe available processing power, also install MKL for R Open. \n\nVisit http://go.microsoft.com/fwlink/?LinkID=698301 for more details."            }        }    } else {        ncores <- RevoUtilsMath::getMKLthreads()        MKLmsg <- ""    }    quiet <- any(match(c("-q", "--silent", "--quiet", "--slave"),         commandArgs()), na.rm = TRUE)    if (!quiet && !identical(system.file(package = "RevoScaleR"),         "")) {        cat("Microsoft R Open ", R.version$major, ".", R.version$minor,             "\n", sep = "")        cat("The enhanced R distribution from Microsoft\n", sep = "")        cat("Microsoft packages Copyright (C)", Revo.version$year,             "Microsoft\n\n")        if (MRS.is.client == FALSE) {            ScaleRPkgName <- "RevoScaleR"            pkgVersion <- utils::packageDescription(ScaleRPkgName)$Version            cat("Loading Microsoft Machine Learning Server packages, version ",                 pkgVersion, ".\n", sep = "")        } else {            RclientPkgName <- "MicrosoftR"            pkgVersion <- utils::packageDescription(RclientPkgName)$Version            cat("Loading Microsoft R Client packages, version ",                 pkgVersion, ". \n", sep = "")            cat("Microsoft R Client limits some functions to available memory.\n")            cat("See: https://go.microsoft.com/fwlink/?linkid=799476 for information\n",                 sep = "")            cat("about additional features.\n\n", sep = "")        }        cat("Type 'readme()' for release notes, privacy() for privacy policy, or\n",             sep = "")        cat("'RevoLicense()' for licensing information.\n\n",             sep = "")        if (MKLmsg == "") {            cat(paste("Using the Intel MKL for parallel mathematical computing (using",                 ncores, "cores).\n", sep = " "))        } else {            cat(MKLmsg, MROversion, sep = " ")        }        cat(paste("Default CRAN mirror snapshot taken on ", repos.date,             ".\n", sep = ""))        cat("See: https://mran.microsoft.com/.", "\n\n", sep = "")        mrupdate::mrCheckForUpdates()    } else if (!quiet) {        cat("Microsoft R Open ", R.version$major, ".", R.version$minor,             "\n", sep = "")        cat("The enhanced R distribution from Microsoft\n", sep = "")        cat("Microsoft packages Copyright (C)", Revo.version$year,             "Microsoft Corporation\n\n")        if (MKLmsg == "") {            cat(paste("Using the Intel MKL for parallel mathematical computing (using",                 ncores, "cores).\n", sep = " "))        } else {            cat(MKLmsg)        }        cat("\nDefault CRAN mirror snapshot taken on ", repos.date,             ".", sep = "")        cat("\n", "See: https://mran.microsoft.com/.", sep = "")        cat("\n\n")    }}), new.env())
23: eval(quote({    r <- getOption("repos")    if (.Platform$OS.type == "unix") {        options(download.file.method = "curl")    }    r["CRAN"] <- RevoUtils::getRevoRepos()    options(repos = r)    MRS.is.client <- RevoUtils:::isMicrosoftRClient()    isMMLSupported <- FALSE    if (identical(.Platform$OS.type, "windows")) {        isMMLSupported <- TRUE    }    if (identical(.Platform$OS.type, "unix") && length(grep("Ubuntu",         Sys.info()["version"]))) {        if (file.exists("/etc/lsb-release")) {            UbuntuReleaseInfo <- scan("/etc/lsb-release", what = "",                 sep = "\n", quiet = TRUE)            if (identical(UbuntuReleaseInfo[2], "DISTRIB_RELEASE=14.04") ||                 identical(UbuntuReleaseInfo[2], "DISTRIB_RELEASE=16.04")) {                isMMLSupported <- TRUE            }        }    }    if (identical(.Platform$OS.type, "unix") && length(grep("el7.x86_64",         Sys.info()["release"]))) {        isMMLSupported <- TRUE    }    if (!identical(system.file(package = "RevoScaleR"), "")) {        options(defaultPackages = c(getOption("defaultPackages"),             "rpart", "lattice", "RevoScaleR", if (!identical(system.file(package = "mrsdeploy"),                 "") && identical(.Platform$OS, "windows") &&                 !identical(Sys.getenv("MRS_IN_DATABASE_HOST_PLATFORM"),                   "1")) "mrsdeploy", if (!identical(system.file(package = "MicrosoftML"),                 "") && isMMLSupported) "MicrosoftML", "RevoMods",             "RevoUtils", "RevoUtilsMath"))        if (nchar(hostName <- Sys.getenv("REVOHADOOPHOST")) &&             nchar(portNumber <- Sys.getenv("REVOHADOOPPORT"))) {            RevoScaleR::rxHdfsConnect(hostName = hostName, portNumber = as.numeric(portNumber))        }    } else {        options(defaultPackages = c(getOption("defaultPackages"),             "RevoUtils"))    }    .RevoVersionShort <- Revo.version$version.string    .RevoVersionShortLen <- regexpr("^.* \\d+\\.\\d+", .RevoVersionShort,         perl = TRUE)    .RevoVersionShort <- substring(.RevoVersionShort, 1, attributes(.RevoVersionShortLen)$match)    if ("setWindowTitle" %in% getNamespaceExports("utils")) {        if (Revo.version$arch == "x86_64") {            .RevoVersionShort <- paste(.RevoVersionShort, "(64-bit)")        }        try(utils::setWindowTitle(paste(" - ", .RevoVersionShort)),             silent = TRUE)    }    if (.Platform$OS.type == "unix" && capabilities("X11")) {        browseAvail <- Sys.which(c("firefox", "mozilla", "galeon",             "opera", "xdg-open", "kfmclient", "gnome-moze-remote"))        if (any(browseAvail != "")) {            options(browser = browseAvail[which(browseAvail !=                 "")[1]])        }    }    if (.Platform$OS.type == "windows") {        options(help_type = "html")    }    load_if_installed <- function(package) {        if (!identical(system.file(package = "RevoUtilsMath"),             "")) {            do.call("library", list(package))            return(TRUE)        } else {            return(FALSE)        }    }    if (identical(system.file(package = "RevoScaleR"), "")) {        if (load_if_installed("RevoUtilsMath")) {            ncores <- RevoUtilsMath::getMKLthreads()        } else {            MROversion <- paste(Revo.version$major, Revo.version$minor,                 sep = ".")            MKLmsg <- "No performance acceleration libraries were detected. To take advantage of \nthe available processing power, also install MKL for R Open. Visit \nhttp://go.microsoft.com/fwlink/?LinkID=698301 for more details.\n"        }        if (Sys.info()["sysname"] == "Darwin") {            options(download.file.method = "libcurl")            hw.ncpu <- try(system("sysctl hw.physicalcpu", intern = TRUE))            if (!inherits(hw.ncpu, "try-error")) {                ncores <- sub("hw.physicalcpu: ", "", hw.ncpu)                MKLmsg = paste0("Multithreaded BLAS/LAPACK libraries detected. Using ",                   ncores, " cores for math algorithms.\n")            }        } else {            if (load_if_installed("RevoUtilsMath")) {                ncores <- RevoUtilsMath::getMKLthreads()                MKLmsg = ""            } else {                MROversion <- paste(Revo.version$major, Revo.version$minor,                   sep = ".")                MKLmsg <- "No performance acceleration libraries were detected. To take advantage of \nthe available processing power, also install MKL for R Open. \n\nVisit http://go.microsoft.com/fwlink/?LinkID=698301 for more details."            }        }    } else {        ncores <- RevoUtilsMath::getMKLthreads()        MKLmsg <- ""    }    quiet <- any(match(c("-q", "--silent", "--quiet", "--slave"),         commandArgs()), na.rm = TRUE)    if (!quiet && !identical(system.file(package = "RevoScaleR"),         "")) {        cat("Microsoft R Open ", R.version$major, ".", R.version$minor,             "\n", sep = "")        cat("The enhanced R distribution from Microsoft\n", sep = "")        cat("Microsoft packages Copyright (C)", Revo.version$year,             "Microsoft\n\n")        if (MRS.is.client == FALSE) {            ScaleRPkgName <- "RevoScaleR"            pkgVersion <- utils::packageDescription(ScaleRPkgName)$Version            cat("Loading Microsoft Machine Learning Server packages, version ",                 pkgVersion, ".\n", sep = "")        } else {            RclientPkgName <- "MicrosoftR"            pkgVersion <- utils::packageDescription(RclientPkgName)$Version            cat("Loading Microsoft R Client packages, version ",                 pkgVersion, ". \n", sep = "")            cat("Microsoft R Client limits some functions to available memory.\n")            cat("See: https://go.microsoft.com/fwlink/?linkid=799476 for information\n",                 sep = "")            cat("about additional features.\n\n", sep = "")        }        cat("Type 'readme()' for release notes, privacy() for privacy policy, or\n",             sep = "")        cat("'RevoLicense()' for licensing information.\n\n",             sep = "")        if (MKLmsg == "") {            cat(paste("Using the Intel MKL for parallel mathematical computing (using",                 ncores, "cores).\n", sep = " "))        } else {            cat(MKLmsg, MROversion, sep = " ")        }        cat(paste("Default CRAN mirror snapshot taken on ", repos.date,             ".\n", sep = ""))        cat("See: https://mran.microsoft.com/.", "\n\n", sep = "")        mrupdate::mrCheckForUpdates()    } else if (!quiet) {        cat("Microsoft R Open ", R.version$major, ".", R.version$minor,             "\n", sep = "")        cat("The enhanced R distribution from Microsoft\n", sep = "")        cat("Microsoft packages Copyright (C)", Revo.version$year,             "Microsoft Corporation\n\n")        if (MKLmsg == "") {            cat(paste("Using the Intel MKL for parallel mathematical computing (using",                 ncores, "cores).\n", sep = " "))        } else {            cat(MKLmsg)        }        cat("\nDefault CRAN mirror snapshot taken on ", repos.date,             ".", sep = "")        cat("\n", "See: https://mran.microsoft.com/.", sep = "")        cat("\n\n")    }}), new.env())
24: eval(expr, p)
25: eval(expr, p)
26: eval.parent(substitute(eval(quote(expr), envir)))
27: local({    r <- getOption("repos")    if (.Platform$OS.type == "unix") {        options(download.file.method = "curl")    }    r["CRAN"] <- RevoUtils::getRevoRepos()    options(repos = r)    MRS.is.client <- RevoUtils:::isMicrosoftRClient()    isMMLSupported <- FALSE    if (identical(.Platform$OS.type, "windows")) {        isMMLSupported <- TRUE    }    if (identical(.Platform$OS.type, "unix") && length(grep("Ubuntu",         Sys.info()["version"]))) {        if (file.exists("/etc/lsb-release")) {            UbuntuReleaseInfo <- scan("/etc/lsb-release", what = "",                 sep = "\n", quiet = TRUE)            if (identical(UbuntuReleaseInfo[2], "DISTRIB_RELEASE=14.04") ||                 identical(UbuntuReleaseInfo[2], "DISTRIB_RELEASE=16.04")) {                isMMLSupported <- TRUE            }        }    }    if (identical(.Platform$OS.type, "unix") && length(grep("el7.x86_64",         Sys.info()["release"]))) {        isMMLSupported <- TRUE    }    if (!identical(system.file(package = "RevoScaleR"), "")) {        options(defaultPackages = c(getOption("defaultPackages"),             "rpart", "lattice", "RevoScaleR", if (!identical(system.file(package = "mrsdeploy"),                 "") && identical(.Platform$OS, "windows") &&                 !identical(Sys.getenv("MRS_IN_DATABASE_HOST_PLATFORM"),                   "1")) "mrsdeploy", if (!identical(system.file(package = "MicrosoftML"),                 "") && isMMLSupported) "MicrosoftML", "RevoMods",             "RevoUtils", "RevoUtilsMath"))        if (nchar(hostName <- Sys.getenv("REVOHADOOPHOST")) &&             nchar(portNumber <- Sys.getenv("REVOHADOOPPORT"))) {            RevoScaleR::rxHdfsConnect(hostName = hostName, portNumber = as.numeric(portNumber))        }    }    else {        options(defaultPackages = c(getOption("defaultPackages"),             "RevoUtils"))    }    .RevoVersionShort <- Revo.version$version.string    .RevoVersionShortLen <- regexpr("^.* \\d+\\.\\d+", .RevoVersionShort,         perl = TRUE)    .RevoVersionShort <- substring(.RevoVersionShort, 1, attributes(.RevoVersionShortLen)$match)    if ("setWindowTitle" %in% getNamespaceExports("utils")) {        if (Revo.version$arch == "x86_64") {            .RevoVersionShort <- paste(.RevoVersionShort, "(64-bit)")        }        try(utils::setWindowTitle(paste(" - ", .RevoVersionShort)),             silent = TRUE)    }    if (.Platform$OS.type == "unix" && capabilities("X11")) {        browseAvail <- Sys.which(c("firefox", "mozilla", "galeon",             "opera", "xdg-open", "kfmclient", "gnome-moze-remote"))        if (any(browseAvail != "")) {            options(browser = browseAvail[which(browseAvail !=                 "")[1]])        }    }    if (.Platform$OS.type == "windows") {        options(help_type = "html")    }    load_if_installed <- function(package) {        if (!identical(system.file(package = "RevoUtilsMath"),             "")) {            do.call("library", list(package))            return(TRUE)        }        else {            return(FALSE)        }    }    if (identical(system.file(package = "RevoScaleR"), "")) {        if (load_if_installed("RevoUtilsMath")) {            ncores <- RevoUtilsMath::getMKLthreads()        }        else {            MROversion <- paste(Revo.version$major, Revo.version$minor,                 sep = ".")            MKLmsg <- "No performance acceleration libraries were detected. To take advantage of \nthe available processing power, also install MKL for R Open. Visit \nhttp://go.microsoft.com/fwlink/?LinkID=698301 for more details.\n"        }        if (Sys.info()["sysname"] == "Darwin") {            options(download.file.method = "libcurl")            hw.ncpu <- try(system("sysctl hw.physicalcpu", intern = TRUE))            if (!inherits(hw.ncpu, "try-error")) {                ncores <- sub("hw.physicalcpu: ", "", hw.ncpu)                MKLmsg = paste0("Multithreaded BLAS/LAPACK libraries detected. Using ",                   ncores, " cores for math algorithms.\n")            }        }        else {            if (load_if_installed("RevoUtilsMath")) {                ncores <- RevoUtilsMath::getMKLthreads()                MKLmsg = ""            }            else {                MROversion <- paste(Revo.version$major, Revo.version$minor,                   sep = ".")                MKLmsg <- "No performance acceleration libraries were detected. To take advantage of \nthe available processing power, also install MKL for R Open. \n\nVisit http://go.microsoft.com/fwlink/?LinkID=698301 for more details."            }        }    }    else {        ncores <- RevoUtilsMath::getMKLthreads()        MKLmsg <- ""    }    quiet <- any(match(c("-q", "--silent", "--quiet", "--slave"),         commandArgs()), na.rm = TRUE)    if (!quiet && !identical(system.file(package = "RevoScaleR"),         "")) {        cat("Microsoft R Open ", R.version$major, ".", R.version$minor,             "\n", sep = "")        cat("The enhanced R distribution from Microsoft\n", sep = "")        cat("Microsoft packages Copyright (C)", Revo.version$year,             "Microsoft\n\n")        if (MRS.is.client == FALSE) {            ScaleRPkgName <- "RevoScaleR"            pkgVersion <- utils::packageDescription(ScaleRPkgName)$Version            cat("Loading Microsoft Machine Learning Server packages, version ",                 pkgVersion, ".\n", sep = "")        }        else {            RclientPkgName <- "MicrosoftR"            pkgVersion <- utils::packageDescription(RclientPkgName)$Version            cat("Loading Microsoft R Client packages, version ",                 pkgVersion, ". \n", sep = "")            cat("Microsoft R Client limits some functions to available memory.\n")            cat("See: https://go.microsoft.com/fwlink/?linkid=799476 for information\n",                 sep = "")            cat("about additional features.\n\n", sep = "")        }        cat("Type 'readme()' for release notes, privacy() for privacy policy, or\n",             sep = "")        cat("'RevoLicense()' for licensing information.\n\n",             sep = "")        if (MKLmsg == "") {            cat(paste("Using the Intel MKL for parallel mathematical computing (using",                 ncores, "cores).\n", sep = " "))        }        else {            cat(MKLmsg, MROversion, sep = " ")        }        cat(paste("Default CRAN mirror snapshot taken on ", repos.date,             ".\n", sep = ""))        cat("See: https://mran.microsoft.com/.", "\n\n", sep = "")        mrupdate::mrCheckForUpdates()    }    else if (!quiet) {        cat("Microsoft R Open ", R.version$major, ".", R.version$minor,             "\n", sep = "")        cat("The enhanced R distribution from Microsoft\n", sep = "")        cat("Microsoft packages Copyright (C)", Revo.version$year,             "Microsoft Corporation\n\n")        if (MKLmsg == "") {            cat(paste("Using the Intel MKL for parallel mathematical computing (using",                 ncores, "cores).\n", sep = " "))        }        else {            cat(MKLmsg)        }        cat("\nDefault CRAN mirror snapshot taken on ", repos.date,             ".", sep = "")        cat("\n", "See: https://mran.microsoft.com/.", sep = "")        cat("\n\n")    }})
An irrecoverable exception occurred. R is aborting now ...
Starting the daemon thread to refresh tokens in background for process with pid = 108


[2020-11-17T10:42:51.117471] The experiment failed. Finalizing run...
Cleaning up all outstanding Run operations, waiting 900.0 seconds
3 items cleaning up...
Cleanup took 0.2237415313720703 seconds
Traceback (most recent call last):
  File "train_with_r.py", line 3, in <module>
    subprocess.check_call(["bash", "-c", "Rscript hello_world.r"])
  File "/azureml-envs/azureml_ef0f23e82f21dcff72679448100a1d19/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['bash', '-c', 'Rscript hello_world.r']' died with <Signals.SIGSEGV: 11>.
```

**Comment by helenproudloveraisingit** [comment]
as a heads up for anyone using this project - the r script examples don't work out of the box. Even after you add r-essentials to the list of dependencies. R doesn't work on the default docker image that is used. The above error is received.

**Comment by j-so** [comment]
Apologies for replying so late. Glad that you were able to work this out, and thank you for sharing your solution!

For now, we won't be altering our docker image to support this. For others facing similar issues, it is recommended that you manage your own docker image - the default docker image provided is meant only to support the example in this repo. 

Here's our doc for setting up your own docker image build pipeline: https://github.com/microsoft/MLOpsPython/blob/master/docs/custom_container.md
