### ISSUE TITLE
Error with ci-build step - Script_name is missing and failure to load azureml_run_type_providers

### ISSUE THREAD

**Issue by buswrecker** [microsoft/MLOpsPython#66]
```
##[section]Starting: Train model using AML with Remote Compute
==============================================================================
Task         : Bash
Description  : Run a Bash script on macOS, Linux, or Windows
Version      : 3.151.3
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/bash
==============================================================================
Generating script.
========================== Starting Command Output ===========================
[command]/bin/bash --noprofile --norc /__w/_temp/229282a5-afb7-470f-942d-4b7f0bcf9134.sh
Failure while loading azureml_run_type_providers. Failed to load entrypoint azureml.PipelineRun = azureml.pipeline.core:PipelineRun._from_dto with exception module 'azureml.pipeline.core' has no attribute 'PipelineRun'.
Failure while loading azureml_run_type_providers. Failed to load entrypoint azureml.ReusedStepRun = azureml.pipeline.core:StepRun._from_reused_dto with exception module 'azureml.pipeline.core' has no attribute 'StepRun'.
Failure while loading azureml_run_type_providers. Failed to load entrypoint azureml.StepRun = azureml.pipeline.core:StepRun._from_dto with exception module 'azureml.pipeline.core' has no attribute 'StepRun'.
Workspace.create(name='mlops8757-AML-WS', subscription_id='aea906c4-b174-444c-9568-9b6bb773121a', resource_group='mlops8757-AML-RG')
Found existing compute target train-cluster so using it.
AmlCompute(workspace=Workspace.create(name='mlops8757-AML-WS', subscription_id='aea906c4-b174-444c-9568-9b6bb773121a', resource_group='mlops8757-AML-RG'), name=train-cluster, id=/subscriptions/aea906c4-b174-444c-9568-9b6bb773121a/resourceGroups/mlops8757-AML-RG/providers/Microsoft.MachineLearningServices/workspaces/mlops8757-AML-WS/computes/train-cluster, type=AmlCompute, provisioning_state=Succeeded, location=eastus, tags=None)
Traceback (most recent call last):
  File "/__w/1/s/ml_service/pipelines/build_train_pipeline.py", line 134, in <module>
    main()
  File "/__w/1/s/ml_service/pipelines/build_train_pipeline.py", line 78, in main
    allow_reuse=False,
  File "/usr/local/lib/python3.7/site-packages/azureml/pipeline/steps/python_script_step.py", line 118, in __init__
    hash_paths=hash_paths)
  File "/usr/local/lib/python3.7/site-packages/azureml/pipeline/core/_python_script_step_base.py", line 33, in __init__
    raise ValueError("script_name is required")
ValueError: script_name is required
##[error]Bash exited with code '1'.
##[section]Finishing: Train model using AML with Remote Compute

```

Script_name` is missing

**Comment by eedorenko** [comment]
Check the variable values. It looks like TRAIN_SCRIPT_PATH variable is not initialized.

**Comment by buswrecker** [comment]
Thank you. It works now. Apologies for missing that variable. I assume that the "failure while loading azureml_run_type_providers" are just warnings?

**Comment by eedorenko** [comment]
Yes, those are just warnings. You can ignore them.
