### ISSUE TITLE
Failed to run pipeline azdo-ci-build-train.yml

### ISSUE THREAD

**Issue by MercyPrasanna** [microsoft/MLOpsPython#94]
I get the below error while publishing the AML service pipeline. Any help to debug this is much appreciated. I had pulled from the latest of this repository yesterday.

##[section]Starting: Publish Azure Machine Learning Pipeline. Python on ML
==============================================================================
Task         : Bash
Description  : Run a Bash script on macOS, Linux, or Windows
Version      : 3.159.3
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/bash
==============================================================================
Generating script.
========================== Starting Command Output ===========================
[command]/bin/bash --noprofile --norc /__w/_temp/365092a7-00dc-4375-b49a-02184648ad9b.sh
Workspace.create(name='mlopcent-AML-WS', subscription_id='601f4351-33bb-4d76-96ca-886940409b3d', resource_group='mlopcent-AML-RG')
Found existing compute target cpucluster so using it.
AmlCompute(workspace=Workspace.create(name='mlopcent-AML-WS', subscription_id='601f4351-33bb-4d76-96ca-886940409b3d', resource_group='mlopcent-AML-RG'), name=cpucluster, id=/subscriptions/601f4351-33bb-4d76-96ca-886940409b3d/resourceGroups/mlopcent-AML-RG/providers/Microsoft.MachineLearningServices/workspaces/mlopcent-AML-WS/computes/cpucluster, type=AmlCompute, provisioning_state=Succeeded, location=centralus, tags=None)
Step Train created
Step Evaluate created
Traceback (most recent call last):
  File "/__w/1/s/ml_service/pipelines/build_train_pipeline.py", line 129, in <module>
    main()
  File "/__w/1/s/ml_service/pipelines/build_train_pipeline.py", line 117, in main
    train_pipeline = Pipeline(workspace=aml_workspace, steps=steps)
  File "/usr/local/lib/python3.7/site-packages/azureml/core/_experiment_method.py", line 93, in wrapper
    return init_func(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/azureml/pipeline/core/pipeline.py", line 179, in __init__
    self._graph = self._graph_builder.build(self._name, steps, finalize=False)
  File "/usr/local/lib/python3.7/site-packages/azureml/pipeline/core/builder.py", line 1331, in build
    graph = self.construct(name, steps)
  File "/usr/local/lib/python3.7/site-packages/azureml/pipeline/core/builder.py", line 1353, in construct
    self.process_collection(steps)
  File "/usr/local/lib/python3.7/site-packages/azureml/pipeline/core/builder.py", line 1389, in process_collection
    builder.process_collection(collection)
  File "/usr/local/lib/python3.7/site-packages/azureml/pipeline/core/builder.py", line 1601, in process_collection
    self._base_builder.process_collection(item)
  File "/usr/local/lib/python3.7/site-packages/azureml/pipeline/core/builder.py", line 1383, in process_collection
    return self.process_step(collection)
  File "/usr/local/lib/python3.7/site-packages/azureml/pipeline/core/builder.py", line 1427, in process_step
    node = step.create_node(self._graph, self._default_datastore, self._context)
  File "/usr/local/lib/python3.7/site-packages/azureml/pipeline/steps/python_script_step.py", line 202, in create_node
    graph=graph, default_datastore=default_datastore, context=context)
  File "/usr/local/lib/python3.7/site-packages/azureml/pipeline/core/_python_script_step_base.py", line 89, in create_node
    context, self._source_directory, self._script_name, self._hash_paths)
  File "/usr/local/lib/python3.7/site-packages/azureml/pipeline/core/builder.py", line 922, in get_source_directory_and_hash_paths
    return Module.process_source_directory_and_hash_paths(self.name, source_directory, script_name, hash_paths)
  File "/usr/local/lib/python3.7/site-packages/azureml/pipeline/core/module.py", line 231, in process_source_directory_and_hash_paths
    % (name, abs_path))
ValueError: Step [Evaluate Model ]: script not found at: /__w/1/s/ code/evaluate/evaluate_model.py. Make sure to specify an appropriate source_directory on the Step or default_source_directory on the Pipeline.

##[error]Bash exited with code '1'.
##[section]Finishing: Publish Azure Machine Learning Pipeline. Python on ML

**Comment by MercyPrasanna** [comment]
Closing this issue as it was due to a leading space in a variable in the variable group definition,
